### ISSUE TITLE
Code in docs not the same as code in repo

### ISSUE THREAD

**Issue by o-az** [spruceid/siwe-next-auth-example#13]
https://docs.login.xyz/integrations/nextauth.js

For example in `pages/api/auth/[...nextauth].ts` in the repo this check doesn't exist but is there in the docs, among other things:

```js
const nextAuthUrl =
  process.env.NEXTAUTH_URL || 
(process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` :
 null);

```

**Comment by obstropolos** [comment]
Hey - taking a look into this now, apologies for the delay on this.

**Comment by obstropolos** [comment]
- This has now been updated to reflect the example in the documentation
- We've also added updated instructions in the documentation to reflect any updates to the next-auth-example that needed fixing (e.g. addressing https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor)
